// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAOjLm14BBoiuwCE_w9Oh7vC5z2UKZ_yY',
    appId: '1:72179439708:web:f373159251380b890c2e99',
    messagingSenderId: '72179439708',
    projectId: 'project-titan-1777a',
    authDomain: 'project-titan-1777a.firebaseapp.com',
    storageBucket: 'project-titan-1777a.firebasestorage.app',
    measurementId: 'G-RB1GZNLNFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDACivOfib9Bzffu16vpqJfzU_pu5hSbdY',
    appId: '1:72179439708:android:2f1f5197b0e59bf40c2e99',
    messagingSenderId: '72179439708',
    projectId: 'project-titan-1777a',
    storageBucket: 'project-titan-1777a.firebasestorage.app',
  );
}